export const REQUEST_FULL_STATE = "DEJA:REQUEST_FULL_STATE";
export const SUBSCRIBE = "DEJA:SUBSCRIBE";
export const UNSUBSCRIBE = "DEJA:UNSUBSCRIBE";
export const FULL_STATE = "DEJA:FULL_STATE";
export const PUBLISH_TO = "DEJA:PUBLISH_TO";
export const REPLAY_ACTION = "DEJA:REPLAY_ACTION";
